version: "3"

services:
  web:
    container_name: webapp
    hostname: webapp
    build:
      context: ./services/web
      dockerfile: Dockerfile.prod
    expose:
      - 5000
    env_file:
      - ./.env.prod

  nginx:
    container_name: reverse
    hostname: reverse
    image: nginx:latest
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 5000:5000
    depends_on:
      - web
