# pyproject.toml
[tool.pytest.ini_options]
addopts = "-ra -vv"
doctest_encoding = "UTF-8"
junit_family = "xunit2"
minversion = "6.0"
testpaths = [
  "tests",
  "integration",
  "unit",
]

[tool.black]
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | \.vscode
  | venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
include = '\.pyi?$'
line-length = 88
