name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.5.0
    - name: Set up Python 3.11
      uses: actions/setup-python@v2.3.3
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r services/web/requirements.txt; 
    - name: Test with pytest
      run: |
        pytest services/web/prepavol;